apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestcraft-backend
  namespace: nestcraft
  labels:
    app: nestcraft
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nestcraft
      component: backend
  template:
    metadata:
      labels:
        app: nestcraft
        component: backend
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: backend
          image: nestcraft/backend:latest
          ports:
            - containerPort: 4000
              name: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: nestcraft-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: nestcraft-config
                  key: PORT
            - name: API_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: nestcraft-config
                  key: API_PREFIX
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: nestcraft-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: nestcraft-config
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: nestcraft-config
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nestcraft-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nestcraft-secrets
                  key: DB_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: nestcraft-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: nestcraft-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nestcraft-secrets
                  key: REDIS_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nestcraft-secrets
                  key: JWT_SECRET
            - name: RATE_LIMIT_TTL
              valueFrom:
                configMapKeyRef:
                  name: nestcraft-config
                  key: RATE_LIMIT_TTL
            - name: RATE_LIMIT_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: nestcraft-config
                  key: RATE_LIMIT_LIMIT
          volumeMounts:
            - name: uploads-storage
              mountPath: /app/uploads
            - name: logs-storage
              mountPath: /app/logs
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /api/v1/health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: uploads-pvc
        - name: logs-storage
          persistentVolumeClaim:
            claimName: logs-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: nestcraft
  labels:
    app: nestcraft
    component: backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: nestcraft
  labels:
    app: nestcraft
    component: backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage

---
apiVersion: v1
kind: Service
metadata:
  name: nestcraft-backend-service
  namespace: nestcraft
  labels:
    app: nestcraft
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: nestcraft
    component: backend

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nestcraft-backend-hpa
  namespace: nestcraft
  labels:
    app: nestcraft
    component: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nestcraft-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 4
          periodSeconds: 60
      selectPolicy: Max
