apiVersion: v1
kind: ConfigMap
metadata:
  name: nestcraft-config
  namespace: nestcraft
  labels:
    app: nestcraft
    component: config
data:
  # Application Configuration
  NODE_ENV: "production"
  API_PREFIX: "api/v1"
  PORT: "4000"
  FRONTEND_PORT: "3000"

  # Database Configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_DATABASE: "nestcraft_prod"

  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

  # Frontend Configuration
  NEXT_TELEMETRY_DISABLED: "1"
  NEXT_PUBLIC_APP_NAME: "NestCraft"

  # Rate Limiting
  RATE_LIMIT_TTL: "900"
  RATE_LIMIT_LIMIT: "100"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: nestcraft
  labels:
    app: nestcraft
    component: database
data:
  POSTGRES_DB: "nestcraft_prod"
  POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: nestcraft
  labels:
    app: nestcraft
    component: cache
data:
  redis.conf: |
    # Redis Configuration for NestCraft
    appendonly yes
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000
    timeout 300
    tcp-keepalive 300
