apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestcraft-frontend
  namespace: nestcraft
  labels:
    app: nestcraft
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestcraft
      component: frontend
  template:
    metadata:
      labels:
        app: nestcraft
        component: frontend
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: frontend
          image: nestcraft/frontend:latest
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: nestcraft-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: nestcraft-config
                  key: FRONTEND_PORT
            - name: NEXT_TELEMETRY_DISABLED
              valueFrom:
                configMapKeyRef:
                  name: nestcraft-config
                  key: NEXT_TELEMETRY_DISABLED
            - name: NEXT_PUBLIC_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: nestcraft-config
                  key: NEXT_PUBLIC_APP_NAME
            - name: NEXT_PUBLIC_API_URL
              value: "http://nestcraft-backend-service:4000/api/v1"
            - name: HOSTNAME
              value: "0.0.0.0"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

---
apiVersion: v1
kind: Service
metadata:
  name: nestcraft-frontend-service
  namespace: nestcraft
  labels:
    app: nestcraft
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: nestcraft
    component: frontend

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nestcraft-frontend-hpa
  namespace: nestcraft
  labels:
    app: nestcraft
    component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nestcraft-frontend
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max
