apiVersion: v1
kind: Secret
metadata:
  name: nestcraft-secrets
  namespace: nestcraft
  labels:
    app: nestcraft
    component: secrets
type: Opaque
data:
  # Database Credentials (base64 encoded)
  # Username: nestcraft_admin
  DB_USERNAME: bmVzdGNyYWZ0X2FkbWlu
  # Password: your-secure-db-password-here
  DB_PASSWORD: eW91ci1zZWN1cmUtZGItcGFzc3dvcmQtaGVyZQ==

  # JWT Secret (base64 encoded)
  # Secret: your-super-secret-jwt-key-2024
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS0yMDI0

  # Redis Password (base64 encoded)
  # Password: your-redis-password-2024
  REDIS_PASSWORD: eW91ci1yZWRpcy1wYXNzd29yZC0yMDI0

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: nestcraft
  labels:
    app: nestcraft
    component: database
type: Opaque
data:
  # PostgreSQL User (base64 encoded)
  POSTGRES_USER: bmVzdGNyYWZ0X2FkbWlu
  # PostgreSQL Password (base64 encoded)
  POSTGRES_PASSWORD: eW91ci1zZWN1cmUtZGItcGFzc3dvcmQtaGVyZQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: nestcraft
  labels:
    app: nestcraft
    component: registry
type: kubernetes.io/dockerconfigjson
data:
  # Docker registry credentials for private images
  # Replace with your actual registry credentials
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ5b3VyLXVzZXJuYW1lIiwicGFzc3dvcmQiOiJ5b3VyLXBhc3N3b3JkIiwiYXV0aCI6ImVXOTFjaTExYzJWeWJtRnRaVHAzYjNWeUxYQmhjM04zYjNKayJ9fX0=
